import pickle

modelname1 = 'anamnesis_modelpr.pkl'
loaded_modelpr = pickle.load(open(modelname1, 'rb'))

modelname_icn = 'anamnesis_model_icn.pkl'
loaded_model_icn = pickle.load(open(modelname_icn, 'rb'))
modelname_gt = 'anamnesis_model_gt.pkl'
loaded_model_gt = pickle.load(open(modelname_gt, 'rb'))
modelname_pp = 'anamnesis_model_pp.pkl'
loaded_model_pp = pickle.load(open(modelname_pp, 'rb'))
modelname_gsd = 'anamnesis_model_gsd.pkl'
loaded_model_gsd = pickle.load(open(modelname_gsd, 'rb'))
modelname_nov = 'anamnesis_model_nov.pkl'
loaded_model_nov = pickle.load(open(modelname_nov, 'rb'))
modelname_prpo = 'anamnesis_model_prpo.pkl'
loaded_model_prpo = pickle.load(open(modelname_prpo, 'rb'))

modelname2 = 'anamnesis_model_plan.pkl'
loaded_model_plan = pickle.load(open(modelname2, 'rb'))
modelname3 = 'anamnesis_model_emer.pkl'
loaded_model_emer = pickle.load(open(modelname3, 'rb'))
modelname4 = 'anamnesis_model_vag.pkl'
loaded_model_vag = pickle.load(open(modelname4, 'rb'))
modelname5 = 'anamnesis_model_break.pkl'
loaded_model_break = pickle.load(open(modelname5, 'rb'))
modelname6 = 'anamnesis_model_pret.pkl'
loaded_model_pret = pickle.load(open(modelname6, 'rb'))
modelname8 = 'anamnesis_model_term.pkl'
loaded_model_term = pickle.load(open(modelname8, 'rb'))

modelname_group12 = 'anamnesis_model_group12.pkl'
loaded_model_group12 = pickle.load(open(modelname_group12, 'rb'))
modelname_group34 = 'anamnesis_model_group34.pkl'
loaded_model_group34 = pickle.load(open(modelname_group34, 'rb'))
modelname_group5 = 'anamnesis_model_group5.pkl'
loaded_model_group5 = pickle.load(open(modelname_group5, 'rb'))

modelname_end = 'anamnesis_model_end.pkl'
loaded_model_end = pickle.load(open(modelname_end, 'rb'))
modelname_foln = 'anamnesis_model_foln.pkl'
loaded_model_foln = pickle.load(open(modelname_foln, 'rb'))
modelname_oocq = 'anamnesis_model_oocq.pkl'
loaded_model_oocq = pickle.load(open(modelname_oocq, 'rb'))

modelname_break2 = 'anamnesis_model_break2.pkl'
loaded_model_break2 = pickle.load(open(modelname_break2, 'rb'))
modelname_gsd2 = 'anamnesis_model_gsd2.pkl'
loaded_model_gsd2 = pickle.load(open(modelname_gsd2, 'rb'))
modelname_nov2 = 'anamnesis_model_nov2.pkl'
loaded_model_nov2 = pickle.load(open(modelname_nov2, 'rb'))
modelname_group122 = 'anamnesis_model_group122.pkl'
loaded_model_group122 = pickle.load(open(modelname_group122, 'rb'))
modelname_group52 = 'anamnesis_model_group52.pkl'
loaded_model_group52 = pickle.load(open(modelname_group52, 'rb'))

modelname_BS = 'anamnesis_model_BS.pkl'
loaded_model_BS = pickle.load(open(modelname_BS, 'rb'))
modelname_3_6B = 'anamnesis_model_3_6B.pkl'
loaded_model_3_6B = pickle.load(open(modelname_3_6B, 'rb'))
modelname_5_3BB = 'anamnesis_model_5_3BB.pkl'
loaded_model_5_3BB = pickle.load(open(modelname_5_3BB, 'rb'))
modelname_56_3BB = 'anamnesis_model_56_3BB.pkl'
loaded_model_56_3BB = pickle.load(open(modelname_56_3BB, 'rb'))

modelname_break3 = 'anamnesis_model_break3.pkl'
loaded_model_break3 = pickle.load(open(modelname_break3, 'rb'))
modelname_gt3 = 'anamnesis_model_gt3.pkl'
loaded_model_gt3 = pickle.load(open(modelname_gt3, 'rb'))
modelname_pp3 = 'anamnesis_model_pp3.pkl'
loaded_model_pp3 = pickle.load(open(modelname_pp3, 'rb'))
modelname_group123 = 'anamnesis_model_group3.pkl'
loaded_model_group123 = pickle.load(open(modelname_group123, 'rb'))
modelname_nov3 = 'anamnesis_model_nov3.pkl'
loaded_model_nov3 = pickle.load(open(modelname_nov3, 'rb'))
modelname_prpo3 = 'anamnesis_model_prpo3.pkl'
loaded_model_prpo3 = pickle.load(open(modelname_prpo3, 'rb'))
modelname_group53 = 'anamnesis_model_group53.pkl'
loaded_model_group53 = pickle.load(open(modelname_group53, 'rb'))

modelname_break3crio = 'anamnesis_model_break3crio.pkl'
loaded_model_break3crio = pickle.load(open(modelname_break3crio, 'rb'))
modelname_gt3crio = 'anamnesis_model_gt3crio.pkl'
loaded_model_gt3crio = pickle.load(open(modelname_gt3crio, 'rb'))
modelname_pp3crio = 'anamnesis_model_pp3crio.pkl'
loaded_model_pp3crio = pickle.load(open(modelname_pp3crio, 'rb'))
modelname_nov3crio = 'anamnesis_model_nov3crio.pkl'
loaded_model_nov3crio = pickle.load(open(modelname_nov3crio, 'rb'))
modelname_prpo3crio = 'anamnesis_model_prpo3crio.pkl'
loaded_model_prpo3crio = pickle.load(open(modelname_prpo3crio, 'rb'))
modelname_group53crio = 'anamnesis_model_group53crio.pkl'
loaded_model_group53crio = pickle.load(open(modelname_group53crio, 'rb'))

modelname_a00_b99 = 'anamnesis_model_a00_b99.pkl'
loaded_model_a00_b99 = pickle.load(open(modelname_a00_b99, 'rb'))
modelname_d50_d89 = 'anamnesis_model_d50_d89.pkl'
loaded_model_d50_d89 = pickle.load(open(modelname_d50_d89, 'rb'))
modelname_d50_d89_2 = 'anamnesis_model_d50_d89_2.pkl'
loaded_model_d50_d89_2 = pickle.load(open(modelname_d50_d89_2, 'rb'))
modelname_d50_d89_eco = 'anamnesis_model_d50_d89_eco.pkl'
loaded_model_d50_d89_eco = pickle.load(open(modelname_d50_d89_eco, 'rb'))
modelname_e00_e90 = 'anamnesis_model_e00_e90.pkl'
loaded_model_e00_e90 = pickle.load(open(modelname_e00_e90, 'rb'))
modelname_e00_e90_2 = 'anamnesis_model_e00_e90_2.pkl'
loaded_model_e00_e90_2 = pickle.load(open(modelname_e00_e90_2, 'rb'))
modelname_e00_e90_eco = 'anamnesis_model_e00_e90_eco.pkl'
loaded_model_e00_e90_eco = pickle.load(open(modelname_e00_e90_eco, 'rb'))
modelname_e00_e90_crio = 'anamnesis_model_e00_e90_crio.pkl'
loaded_model_e00_e90_crio = pickle.load(open(modelname_e00_e90_crio, 'rb'))
modelname_c00_d48 = 'anamnesis_model_c00_d48.pkl'
loaded_model_c00_d48 = pickle.load(open(modelname_c00_d48, 'rb'))
modelname_c00_d48_2 = 'anamnesis_model_c00_d48_2.pkl'
loaded_model_c00_d48_2 = pickle.load(open(modelname_c00_d48_2, 'rb'))
modelname_c00_d48_eco = 'anamnesis_model_c00_d48_eco.pkl'
loaded_model_c00_d48_eco = pickle.load(open(modelname_c00_d48_eco, 'rb'))
modelname_g00_g99 = 'anamnesis_model_g00_g99.pkl'
loaded_model_g00_g99 = pickle.load(open(modelname_g00_g99, 'rb'))
modelname_h00_h59 = 'anamnesis_model_h00_h59.pkl'
loaded_model_h00_h59 = pickle.load(open(modelname_h00_h59, 'rb'))
modelname_h60_h95 = 'anamnesis_model_h60_h95.pkl'
loaded_model_h60_h95 = pickle.load(open(modelname_h60_h95, 'rb'))
modelname_h60_h95_eco = 'anamnesis_model_h60_h95_eco.pkl'
loaded_model_h60_h95_eco = pickle.load(open(modelname_h60_h95_eco, 'rb'))
modelname_i00_i99 = 'anamnesis_model_i00_i99.pkl'
loaded_model_i00_i99 = pickle.load(open(modelname_i00_i99, 'rb'))
modelname_i00_i99_2 = 'anamnesis_model_i00_i99_2.pkl'
loaded_model_i00_i99_2 = pickle.load(open(modelname_i00_i99_2, 'rb'))
modelname_j00_j99 = 'anamnesis_model_j00_j99.pkl'
loaded_model_j00_j99 = pickle.load(open(modelname_j00_j99, 'rb'))
modelname_j00_j99_2 = 'anamnesis_model_j00_j99_2.pkl'
loaded_model_j00_j99_2 = pickle.load(open(modelname_j00_j99_2, 'rb'))
modelname_j00_j99_eco = 'anamnesis_model_j00_j99_eco.pkl'
loaded_model_j00_j99_eco = pickle.load(open(modelname_j00_j99_eco, 'rb'))
modelname_j00_j99_crio = 'anamnesis_model_j00_j99_crio.pkl'
loaded_model_j00_j99_crio = pickle.load(open(modelname_j00_j99_crio, 'rb'))
modelname_k00_k93 = 'anamnesis_model_k00_k93.pkl'
loaded_model_k00_k93 = pickle.load(open(modelname_k00_k93, 'rb'))
modelname_l00_l99 = 'anamnesis_model_l00_l99.pkl'
loaded_model_l00_l99 = pickle.load(open(modelname_l00_l99, 'rb'))
modelname_l00_l99_crio = 'anamnesis_model_l00_l99_crio.pkl'
loaded_model_l00_l99_crio = pickle.load(open(modelname_l00_l99_crio, 'rb'))
modelname_m00_m99 = 'anamnesis_model_m00_m99.pkl'
loaded_model_m00_m99 = pickle.load(open(modelname_m00_m99, 'rb'))
modelname_m00_m99_eco = 'anamnesis_model_m00_m99_eco.pkl'
loaded_model_m00_m99_eco = pickle.load(open(modelname_m00_m99_eco, 'rb'))
modelname_m00_m99_crio = 'anamnesis_model_m00_m99_crio.pkl'
loaded_model_m00_m99_crio = pickle.load(open(modelname_m00_m99_crio, 'rb'))
modelname_n00_n99 = 'anamnesis_model_n00_n99.pkl'
loaded_model_n00_n99 = pickle.load(open(modelname_n00_n99, 'rb'))
modelname_n00_n99_2 = 'anamnesis_model_n00_n99_2.pkl'
loaded_model_n00_n99_2 = pickle.load(open(modelname_n00_n99_2, 'rb'))
modelname_n00_n99_eco = 'anamnesis_model_n00_n99_eco.pkl'
loaded_model_n00_n99_eco = pickle.load(open(modelname_n00_n99_eco, 'rb'))
modelname_p00_p96 = 'anamnesis_model_p00_p96.pkl'
loaded_model_p00_p96 = pickle.load(open(modelname_p00_p96, 'rb'))
modelname_p00_p96_2 = 'anamnesis_model_p00_p96_2.pkl'
loaded_model_p00_p96_2 = pickle.load(open(modelname_p00_p96_2, 'rb'))
modelname_p00_p96_eco = 'anamnesis_model_p00_p96_eco.pkl'
loaded_model_p00_p96_eco = pickle.load(open(modelname_p00_p96_eco, 'rb'))
modelname_p00_p96_crio = 'anamnesis_model_p00_p96_crio.pkl'
loaded_model_p00_p96_crio = pickle.load(open(modelname_p00_p96_crio, 'rb'))
modelname_q00_q99 = 'anamnesis_model_q00_q99.pkl'
loaded_model_q00_q99 = pickle.load(open(modelname_q00_q99, 'rb'))
